# Generated by Django 3.1.14 on 2023-07-27 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('add_date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CourseDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('description', models.CharField(max_length=100000)),
                ('price', models.IntegerField()),
                ('duration', models.CharField(max_length=100)),
                ('base_technology', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_interface1.technology')),
            ],
        ),
    ]
